# Generated by Django 2.2.4 on 2019-09-05 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'get_latest_by': 'recibido', 'ordering': ['-recibido'], 'verbose_name': 'Plan de Implementación', 'verbose_name_plural': 'Planes de Implementación'},
        ),
        migrations.AddField(
            model_name='plan',
            name='páginas',
            field=models.IntegerField(default=0, verbose_name='Páginas en total'),
        ),
        migrations.AddField(
            model_name='plan',
            name='páginas_quitadas',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Páginas quitadas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='recibido',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de recepción'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='documento',
            field=models.FileField(upload_to='planes', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='estatus',
            field=models.SmallIntegerField(choices=[(1, 'Documento requiere revisión'), (2, 'Documento ha sido revisado')], default=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fuente',
            field=models.URLField(max_length=255, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2019, 5, 29, 0, 0), verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='revisado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
    ]
