# Generated by Django 2.0.1 on 2018-01-29 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=16, verbose_name='Departamento')),
                ('entidad', models.CharField(max_length=255, verbose_name='Entidad')),
                ('slug', models.SlugField(unique=True, verbose_name='CUCE')),
                ('objeto', models.CharField(max_length=512, verbose_name='Objeto')),
                ('modalidad', models.CharField(max_length=64, verbose_name='Modalidad')),
                ('tipo', models.CharField(max_length=16, verbose_name='Tipo')),
                ('estatus', models.SmallIntegerField(choices=[(1, 'Nueva'), (2, 'Convocatoria no necesita revisión'), (3, 'Convocatoria requiere documento para su revisión'), (4, 'Documento requiere revisión'), (5, 'Documento en revisión'), (6, 'Convocatoria libre de software privativo'), (7, 'Convocatoria contaminada con software privativo')], default=1, verbose_name='Estatus')),
                ('añadida', models.DateTimeField(verbose_name='Añadida')),
                ('publicada', models.DateField(verbose_name='Fecha de publicación')),
                ('presentada', models.DateField(verbose_name='Fecha de presentación')),
                ('impugnada', models.DateField(blank=True, null=True, verbose_name='Impugnada')),
                ('monto_bob', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Monto Bs.')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Monto $us.')),
                ('monto_eur', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Monto €')),
                ('contacto', models.CharField(max_length=64, verbose_name='Contacto')),
                ('documento', models.FileField(blank=True, upload_to='files', verbose_name='D.B.C.')),
                ('arch', models.CharField(editable=False, max_length=16, verbose_name='D.B.C. Arch')),
                ('añadido', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='D.B.C. añadido')),
                ('revisado', models.DateTimeField(blank=True, null=True, verbose_name='D.B.C. revisado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas de la revisión')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['-publicada'],
                'get_latest_by': 'añadida',
            },
        ),
    ]
