# Generated by Django 2.0.1 on 2018-02-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='enlace',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
