# Generated by Django 2.0.1 on 2018-02-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_convocatoria_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='enlace',
            field=models.URLField(max_length=255),
        ),
    ]
