# Generated by Django 2.1.5 on 2019-01-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0004_auto_20180209_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='estatus',
            field=models.SmallIntegerField(choices=[(1, 'Nueva'), (2, 'Convocatoria no necesita revisión'), (3, 'Convocatoria requiere documento para su revisión'), (4, 'Documento requiere revisión'), (5, 'Documento en revisión'), (6, 'Convocatoria libre de software privativo'), (7, 'Convocatoria contaminada con software privativo'), (8, 'Convocatoria es un ejemplo')], default=1, verbose_name='Estatus'),
        ),
    ]
