# Generated by Django 2.1.5 on 2019-01-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0005_auto_20190112_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='enlace',
            field=models.URLField(max_length=512),
        ),
    ]
